# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the TypeScript project
RUN npm run build

# Expose port if running in SSE mode (optional)
EXPOSE 3000

# Start the server
CMD [ "node", "dist/index.js" ]
